# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/maze_display.xdc

# XDC: new/Basys3.xdc

# XDC: C:/Users/Dell/Documents/uni_docs/cs/dld/project_stuff/dld_final_project/joystick_stuff/Basys3-Joystick-Interfacing/test.srcs/constrs_1/imports/constraints/Basys3_Master.xdc

# XDC: new/before_joystick.xdc

# IP: C:/Users/Dell/Documents/uni_docs/cs/dld/project_stuff/dld_final_project/joystick_stuff/Basys3-Joystick-Interfacing/test.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] -quiet
